"""Base class for auto-generated step builders.

A StepBuilder collects constructor arguments via fluent methods and
implements ``StepProtocol`` so it can be used directly in ``seq([...])``.
When executed, it builds the real Step and delegates to it.

Builder classes are generated by raccoon codegen from ``@dsl_step``-decorated
Step classes.  Each ``__init__`` parameter becomes a fluent setter method,
and a snake_case factory function is generated alongside.
"""

from __future__ import annotations

from abc import abstractmethod
from typing import Optional, Union, TYPE_CHECKING

from .base import Step, StepAnomalyCallback

if TYPE_CHECKING:
    from raccoon.robot.api import GenericRobot


class StepBuilder(Step):
    """Base class for generated step builders.

    Subclasses must implement ``_build()`` to construct the real Step
    from the collected parameters.

    Since StepBuilder extends Step, it satisfies StepProtocol and can be
    used anywhere a Step is expected (seq, parallel, mission step lists).
    """

    _composite = True

    def __init__(self) -> None:
        super().__init__()
        self._builder_anomaly_callback: Optional[StepAnomalyCallback] = None
        self._builder_skip_timing: bool = False
        self._resolved: Optional[Step] = None

    def on_anomaly(self, callback_or_step: "Union[StepAnomalyCallback, Step]") -> "StepBuilder":
        """Register a callback or step invoked when a timing anomaly is detected.

        Accepts either an async callback ``(step, robot) -> None`` or a
        ``Step`` instance to run when the anomaly fires::

            drive_forward(25).on_anomaly(my_handler)

            async def my_handler(step, robot):
                ...

            # Or pass a step directly:
            drive_forward(25).on_anomaly(play_sound())
        """
        if isinstance(callback_or_step, Step):
            anomaly_step = callback_or_step

            async def _step_callback(_anomalous: "Step", robot: "GenericRobot") -> None:
                await anomaly_step.run_step(robot)

            self._builder_anomaly_callback = _step_callback
        else:
            self._builder_anomaly_callback = callback_or_step
        return self

    def skip_timing(self) -> "StepBuilder":
        """Exclude this step from timing anomaly tracking.

        Use for steps whose duration is inherently variable
        (e.g., condition-only drives, user-input waits).
        """
        self._builder_skip_timing = True
        return self

    @abstractmethod
    def _build(self) -> Step:
        """Construct the real Step from collected parameters."""
        raise NotImplementedError

    def resolve(self) -> Step:
        """Build the underlying Step and apply any chained options.

        Idempotent — composite constructors call this to replace a builder
        with its real Step at validation time, so resource conflict checks
        and signature lookups see the actual underlying step rather than
        an empty builder placeholder. Subsequent calls return the cached
        instance, so this is safe even if a builder ends up reachable from
        multiple parents.

        Once a builder has been resolved, mutating it via ``on_anomaly()``
        or ``skip_timing()`` is a no-op against the cached step — call
        those before placing the builder inside a composite.
        """
        if self._resolved is None:
            step = self._build()
            if self._builder_anomaly_callback is not None:
                step._anomaly_callback = self._builder_anomaly_callback
            if self._builder_skip_timing:
                step._skip_timing = True
            self._resolved = step
        return self._resolved

    async def _execute_step(self, robot: "GenericRobot") -> None:
        """Execute via the resolved underlying step.

        Composites resolve their children eagerly, so this path is only
        reached when a builder is run directly (e.g. as the root of a
        mission's ``sequence()``).
        """
        await self.resolve().run_step(robot)

    def _generate_signature(self) -> str:
        return self.resolve()._generate_signature()
