"""Contributor-facing motion step DSL built on top of the native motion controllers."""

from .motion_step import MotionStep
from .drive import (
    DriveForward, DriveBackward, StrafeLeft, StrafeRight,
)
from .drive_dsl import (
    drive_forward, drive_backward, strafe_left, strafe_right,
)
from .drive_angle import DriveAngle
from .drive_angle_dsl import drive_angle
from .arc import Arc, DriveArcLeft, DriveArcRight, DriveArc
from .arc_dsl import drive_arc_left, drive_arc_right, drive_arc
from .stop import Stop
from .stop_dsl import stop
from .turn import TurnLeft, TurnRight
from .turn_dsl import turn_left, turn_right
from .heading_reference import MarkHeadingReference, turn_to_heading
from .heading_reference_dsl import mark_heading_reference
from .move_until import (
    SurfaceColor,
    MoveUntil,
    MoveUntilConfig,
    move_until,
    drive_until_black,
    drive_until_white,
    DriveForwardUntilBlack,
    drive_forward_until_black,
    DriveForwardUntilWhite,
    drive_forward_until_white,
    DriveBackwardUntilBlack,
    drive_backward_until_black,
    DriveBackwardUntilWhite,
    drive_backward_until_white,
    turn_until_black,
    turn_until_white,
    TurnLeftUntilBlack,
    turn_left_until_black,
    TurnLeftUntilWhite,
    turn_left_until_white,
    TurnRightUntilBlack,
    turn_right_until_black,
    TurnRightUntilWhite,
    turn_right_until_white,
    strafe_until_black,
    strafe_until_white,
    StrafeLeftUntilBlack,
    strafe_left_until_black,
    StrafeLeftUntilWhite,
    strafe_left_until_white,
    StrafeRightUntilBlack,
    strafe_right_until_black,
    StrafeRightUntilWhite,
    strafe_right_until_white,
    DriveAngleUntilBlack,
    drive_angle_until_black,
    DriveAngleUntilWhite,
    drive_angle_until_white,
)
from .lineup import (
    lineup,
    forward_lineup_on_black,
    forward_lineup_on_white,
    backward_lineup_on_black,
    backward_lineup_on_white,
    strafe_right_lineup_on_black,
    strafe_right_lineup_on_white,
    strafe_left_lineup_on_black,
    strafe_left_lineup_on_white,
    CorrectionSide,
    SingleSensorCrossing,
    SingleSensorLineupConfig,
    forward_single_lineup,
    backward_single_lineup,
)
from .wall_align import (
    WallAlign,
    WallDirection,
    BumpResult,
    WallAlignForward,
    WallAlignBackward,
    WallAlignStrafeLeft,
    WallAlignStrafeRight,
)
from .wall_align_dsl import (
    wall_align_forward,
    wall_align_backward,
    wall_align_strafe_left,
    wall_align_strafe_right,
)
from .line_follow import (
    LineFollow,
    LineFollowConfig,
    LineSide,
    SingleSensorLineFollow,
    SingleLineFollowConfig,
    SingleSensorLineFollowUntilBlack,
    SingleLineFollowUntilBlackConfig,
    FollowLine,
    FollowLineUntilBothBlack,
    FollowLineSingle,
    FollowLineSingleUntilBlack,
    DirectionalLineFollow,
    DirectionalLineFollowConfig,
    DirectionalSingleLineFollow,
    DirectionalSingleLineFollowConfig,
    DirectionalFollowLine,
    DirectionalFollowLineUntilBothBlack,
    StrafeFollowLine,
    StrafeFollowLineUntilBothBlack,
    StrafeFollowLineSingle,
    StrafeFollowLineSingleUntilBlack,
    DirectionalFollowLineSingle,
    DirectionalFollowLineSingleUntilBlack,
)
from .line_follow_dsl import (
    follow_line,
    follow_line_until_both_black,
    follow_line_single,
    follow_line_single_until_black,
    directional_follow_line,
    directional_follow_line_until_both_black,
    strafe_follow_line,
    strafe_follow_line_until_both_black,
    strafe_follow_line_single,
    strafe_follow_line_single_until_black,
    directional_follow_line_single,
    directional_follow_line_single_until_black,
)

from .at_distance import WaitUntilDistance
from .at_distance_dsl import wait_until_distance
from .tune_drive import TuneDrive
from .tune_drive_dsl import tune_drive
from .characterize_drive import CharacterizeDrive
from .characterize_drive_dsl import characterize_drive
from .auto_tune import (
    AutoTune,
    AutoTuneVelocity,
    AutoTuneMotion,
)
from .auto_tune_dsl import (
    auto_tune,
    auto_tune_velocity,
    auto_tune_motion,
)

__all__ = [
    # Base
    "MotionStep",
    # Basic motion
    "DriveForward",
    "drive_forward",
    "DriveBackward",
    "drive_backward",
    "Stop",
    "stop",
    "StrafeLeft",
    "strafe_left",
    "StrafeRight",
    "strafe_right",
    "DriveAngle",
    "drive_angle",
    "Arc",
    "DriveArcLeft",
    "drive_arc_left",
    "DriveArcRight",
    "drive_arc_right",
    "DriveArc",
    "drive_arc",
    "TurnLeft",
    "turn_left",
    "TurnRight",
    "turn_right",
    # Heading reference
    "MarkHeadingReference",
    "mark_heading_reference",
    "turn_to_heading",
    # Move until sensor
    "SurfaceColor",
    "MoveUntil",
    "MoveUntilConfig",
    "move_until",
    "drive_until_black",
    "drive_until_white",
    "DriveForwardUntilBlack",
    "drive_forward_until_black",
    "DriveForwardUntilWhite",
    "drive_forward_until_white",
    "DriveBackwardUntilBlack",
    "drive_backward_until_black",
    "DriveBackwardUntilWhite",
    "drive_backward_until_white",
    "turn_until_black",
    "turn_until_white",
    "TurnLeftUntilBlack",
    "turn_left_until_black",
    "TurnLeftUntilWhite",
    "turn_left_until_white",
    "TurnRightUntilBlack",
    "turn_right_until_black",
    "TurnRightUntilWhite",
    "turn_right_until_white",
    "strafe_until_black",
    "strafe_until_white",
    "StrafeLeftUntilBlack",
    "strafe_left_until_black",
    "StrafeLeftUntilWhite",
    "strafe_left_until_white",
    "StrafeRightUntilBlack",
    "strafe_right_until_black",
    "StrafeRightUntilWhite",
    "strafe_right_until_white",
    "DriveAngleUntilBlack",
    "drive_angle_until_black",
    "DriveAngleUntilWhite",
    "drive_angle_until_white",
    # Lineup
    "lineup",
    "forward_lineup_on_black",
    "forward_lineup_on_white",
    "backward_lineup_on_black",
    "backward_lineup_on_white",
    "strafe_right_lineup_on_black",
    "strafe_right_lineup_on_white",
    "strafe_left_lineup_on_black",
    "strafe_left_lineup_on_white",
    "CorrectionSide",
    "SingleSensorCrossing",
    "SingleSensorLineupConfig",
    "forward_single_lineup",
    "backward_single_lineup",
    # Wall align
    "WallAlign",
    "WallDirection",
    "BumpResult",
    "WallAlignForward",
    "wall_align_forward",
    "WallAlignBackward",
    "wall_align_backward",
    "WallAlignStrafeLeft",
    "wall_align_strafe_left",
    "WallAlignStrafeRight",
    "wall_align_strafe_right",
    # Line follow
    "LineFollow",
    "LineFollowConfig",
    "LineSide",
    "SingleSensorLineFollow",
    "SingleLineFollowConfig",
    "SingleSensorLineFollowUntilBlack",
    "SingleLineFollowUntilBlackConfig",
    "FollowLine",
    "follow_line",
    "FollowLineUntilBothBlack",
    "follow_line_until_both_black",
    "FollowLineSingle",
    "follow_line_single",
    "FollowLineSingleUntilBlack",
    "follow_line_single_until_black",
    # Directional line follow
    "DirectionalLineFollow",
    "DirectionalLineFollowConfig",
    "DirectionalSingleLineFollow",
    "DirectionalSingleLineFollowConfig",
    "DirectionalFollowLine",
    "directional_follow_line",
    "DirectionalFollowLineUntilBothBlack",
    "directional_follow_line_until_both_black",
    "StrafeFollowLine",
    "strafe_follow_line",
    "StrafeFollowLineUntilBothBlack",
    "strafe_follow_line_until_both_black",
    "StrafeFollowLineSingle",
    "strafe_follow_line_single",
    "StrafeFollowLineSingleUntilBlack",
    "strafe_follow_line_single_until_black",
    "DirectionalFollowLineSingle",
    "directional_follow_line_single",
    "DirectionalFollowLineSingleUntilBlack",
    "directional_follow_line_single_until_black",
    # Distance wait
    "WaitUntilDistance",
    "wait_until_distance",
    # Drive telemetry
    "TuneDrive",
    "tune_drive",
    # Drive characterization
    "CharacterizeDrive",
    "characterize_drive",
    # Auto-tune PID
    "AutoTune",
    "auto_tune",
    "AutoTuneVelocity",
    "auto_tune_velocity",
    "AutoTuneMotion",
    "auto_tune_motion",
]
