"""Robot geometry calculations for sensor and wheel positions.

This module provides dataclasses for representing sensor and wheel positions,
and a mixin class for computing distances and angles between elements.

Example usage:
    from raccoon.robot.geometry import RobotGeometry, SensorPosition, WheelPosition

    class Robot(GenericRobot, RobotGeometry):
        width_cm = 15.0
        length_cm = 22.0
        rotation_center_forward_cm = 0.0
        rotation_center_strafe_cm = 0.0

        _sensor_positions = {
            defs.front_left_ir_sensor: SensorPosition(forward_cm=8.8, strafe_cm=3.75),
        }

        _wheel_positions = {
            defs.front_left_motor: WheelPosition(forward_cm=6.0, strafe_cm=9.5),
        }

    robot = Robot()
    pos = robot.sensor_position(robot.defs.front_left_ir_sensor)
    print(f"Sensor at: {pos.forward_cm}cm forward, {pos.strafe_cm}cm left")

    wheel_pos = robot.wheel_position(robot.defs.front_left_motor)
    print(f"Wheel at: {wheel_pos.forward_cm}cm forward")
"""

from dataclasses import dataclass
import math
from typing import Dict, Optional, Any


@dataclass
class SensorPosition:
    """Position of a sensor relative to robot geometric center.

    Attributes:
        forward_cm: Distance forward from center (positive = front of robot)
        strafe_cm: Distance left from center (positive = left side of robot)
        clearance_cm: Sensor clearance/detection radius
    """

    forward_cm: float
    strafe_cm: float
    clearance_cm: float = 0.0


@dataclass
class WheelPosition:
    """Position of a wheel relative to robot geometric center.

    Attributes:
        forward_cm: Distance forward from center (positive = front of robot)
        strafe_cm: Distance left from center (positive = left side of robot)
    """

    forward_cm: float
    strafe_cm: float


class RobotGeometry:
    """Mixin class providing geometry calculations for robot positioning.

    This class should be used as a mixin with GenericRobot. Subclasses must
    define the following class attributes (typically generated by codegen):

    - width_cm: Robot width in centimeters
    - length_cm: Robot length in centimeters
    - rotation_center_forward_cm: Offset from geometric center to rotation center (forward axis)
    - rotation_center_strafe_cm: Offset from geometric center to rotation center (strafe axis)
    - _sensor_positions: Dict mapping sensor objects to SensorPosition instances
    - _wheel_positions: Dict mapping motor objects to WheelPosition instances

    The mixin provides computed methods for:
    - Getting sensor/wheel positions
    - Computing distances between sensors
    - Computing distances from sensors to rotation center
    - Computing angles from center to sensors
    """

    # Override these in generated Robot class
    width_cm: float = 0.0
    length_cm: float = 0.0
    rotation_center_forward_cm: float = 0.0
    rotation_center_strafe_cm: float = 0.0

    # Sensor registry: maps sensor instance to position
    _sensor_positions: Dict[Any, SensorPosition] = {}
    _wheel_positions: Dict[Any, WheelPosition] = {}

    def sensor_position(self, sensor: Any) -> Optional[SensorPosition]:
        """Get the position of a sensor relative to robot center.

        Args:
            sensor: The sensor object (pass defs.sensor_name)

        Returns:
            SensorPosition if found, None otherwise
        """
        return self._sensor_positions.get(sensor)

    def wheel_position(self, motor: Any) -> Optional[WheelPosition]:
        """Get the position of a wheel by its motor object.

        Args:
            motor: The motor object (pass defs.motor_name)

        Returns:
            WheelPosition if found, None otherwise
        """
        return self._wheel_positions.get(motor)

    def distance_between_sensors(self, sensor_a: Any, sensor_b: Any) -> float:
        """Calculate the Euclidean distance between two sensors.

        Args:
            sensor_a: First sensor object
            sensor_b: Second sensor object

        Returns:
            Distance in centimeters

        Raises:
            ValueError: If either sensor is not found in geometry
        """
        pos_a = self._sensor_positions.get(sensor_a)
        pos_b = self._sensor_positions.get(sensor_b)

        if pos_a is None:
            raise ValueError(f"Sensor not found in geometry: {sensor_a}")
        if pos_b is None:
            raise ValueError(f"Sensor not found in geometry: {sensor_b}")

        return math.hypot(
            pos_a.forward_cm - pos_b.forward_cm,
            pos_a.strafe_cm - pos_b.strafe_cm,
        )

    def sensor_to_rotation_center(self, sensor: Any) -> float:
        """Calculate the distance from a sensor to the rotation center.

        This is useful for arc calculations during turns.

        Args:
            sensor: The sensor object

        Returns:
            Distance in centimeters

        Raises:
            ValueError: If sensor is not found in geometry
        """
        pos = self._sensor_positions.get(sensor)
        if pos is None:
            raise ValueError(f"Sensor not found in geometry: {sensor}")

        return math.hypot(
            pos.forward_cm - self.rotation_center_forward_cm,
            pos.strafe_cm - self.rotation_center_strafe_cm,
        )

    def sensor_to_geometric_center(self, sensor: Any) -> float:
        """Calculate the distance from a sensor to the geometric center.

        Args:
            sensor: The sensor object

        Returns:
            Distance in centimeters

        Raises:
            ValueError: If sensor is not found in geometry
        """
        pos = self._sensor_positions.get(sensor)
        if pos is None:
            raise ValueError(f"Sensor not found in geometry: {sensor}")

        return math.hypot(pos.forward_cm, pos.strafe_cm)

    def sensor_angle_from_center(self, sensor: Any) -> float:
        """Calculate the angle from geometric center to a sensor.

        The angle is measured in radians, with 0 being forward and
        positive angles going counter-clockwise (to the left).

        Args:
            sensor: The sensor object

        Returns:
            Angle in radians (0 = forward, π/2 = left, -π/2 = right)

        Raises:
            ValueError: If sensor is not found in geometry
        """
        pos = self._sensor_positions.get(sensor)
        if pos is None:
            raise ValueError(f"Sensor not found in geometry: {sensor}")

        return math.atan2(pos.strafe_cm, pos.forward_cm)

    def sensor_angle_from_rotation_center(self, sensor: Any) -> float:
        """Calculate the angle from rotation center to a sensor.

        The angle is measured in radians, with 0 being forward and
        positive angles going counter-clockwise (to the left).

        Args:
            sensor: The sensor object

        Returns:
            Angle in radians (0 = forward, π/2 = left, -π/2 = right)

        Raises:
            ValueError: If sensor is not found in geometry
        """
        pos = self._sensor_positions.get(sensor)
        if pos is None:
            raise ValueError(f"Sensor not found in geometry: {sensor}")

        delta_forward = pos.forward_cm - self.rotation_center_forward_cm
        delta_strafe = pos.strafe_cm - self.rotation_center_strafe_cm

        return math.atan2(delta_strafe, delta_forward)

    def all_sensors(self) -> Dict[Any, SensorPosition]:
        """Get all sensor positions.

        Returns:
            Dictionary mapping sensor objects to their positions
        """
        return dict(self._sensor_positions)

    def all_wheels(self) -> Dict[Any, WheelPosition]:
        """Get all wheel positions.

        Returns:
            Dictionary mapping motor objects to their positions
        """
        return dict(self._wheel_positions)
