# This file was generated by gen_defs.py — do not edit by hand.
from libstp.foundation import Deadzone, Feedforward, MotorCalibration, PidGains
from libstp.hal import Motor


class Defs:
    left_motor = Motor(
        port=0,
        invert_command=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.1, kV=0.05, kA=0.01),
            pid=PidGains(kp=1.0, ki=0.1, kd=0.05),
            deadzone=Deadzone(
                enable=True,
                zero_window_percent=2.0,
                start_percent=5.0,
                release_percent=3.0,
            ),
            max_percent_output=100.0,
            ticks_to_rad=0.001534,
            vel_lpf_alpha=0.8,
            invert_meas=False,
            invert_cmd=False,
        ),
    )
    right_motor = Motor(
        port=0,
        invert_command=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.1, kV=0.05, kA=0.01),
            pid=PidGains(kp=1.0, ki=0.1, kd=0.05),
            deadzone=Deadzone(
                enable=True,
                zero_window_percent=2.0,
                start_percent=5.0,
                release_percent=3.0,
            ),
            max_percent_output=100.0,
            ticks_to_rad=0.001534,
            vel_lpf_alpha=0.8,
            invert_meas=False,
            invert_cmd=False,
        ),
    )

    # List of drive motors for distance calibration
    drive_motors = [left_motor, right_motor]


__all__ = ["Defs"]
