"""Base class for auto-generated step builders.

A StepBuilder collects constructor arguments via fluent methods and
implements ``StepProtocol`` so it can be used directly in ``seq([...])``.
When executed, it builds the real Step and delegates to it.

Builder classes are generated by raccoon codegen from ``@dsl_step``-decorated
Step classes.  Each ``__init__`` parameter becomes a fluent setter method,
and a snake_case factory function is generated alongside.
"""

from __future__ import annotations

from abc import abstractmethod
from typing import TYPE_CHECKING

from .base import Step

if TYPE_CHECKING:
    from libstp.robot.api import GenericRobot


class StepBuilder(Step):
    """Base class for generated step builders.

    Subclasses must implement ``_build()`` to construct the real Step
    from the collected parameters.

    Since StepBuilder extends Step, it satisfies StepProtocol and can be
    used anywhere a Step is expected (seq, parallel, mission step lists).
    """

    def __init__(self) -> None:
        super().__init__()

    @abstractmethod
    def _build(self) -> Step:
        """Construct the real Step from collected parameters."""
        raise NotImplementedError

    async def _execute_step(self, robot: "GenericRobot") -> None:
        """Build the step and execute it."""
        step = self._build()
        await step.run_step(robot)

    def _generate_signature(self) -> str:
        step = self._build()
        return step._generate_signature()
