"""Base class for auto-generated step builders.

A StepBuilder collects constructor arguments via fluent methods and
implements ``StepProtocol`` so it can be used directly in ``seq([...])``.
When executed, it builds the real Step and delegates to it.

Builder classes are generated by raccoon codegen from ``@dsl_step``-decorated
Step classes.  Each ``__init__`` parameter becomes a fluent setter method,
and a snake_case factory function is generated alongside.
"""

from __future__ import annotations

from abc import abstractmethod
from typing import Optional, TYPE_CHECKING

from .base import Step, StepAnomalyCallback

if TYPE_CHECKING:
    from libstp.robot.api import GenericRobot


class StepBuilder(Step):
    """Base class for generated step builders.

    Subclasses must implement ``_build()`` to construct the real Step
    from the collected parameters.

    Since StepBuilder extends Step, it satisfies StepProtocol and can be
    used anywhere a Step is expected (seq, parallel, mission step lists).
    """

    def __init__(self) -> None:
        super().__init__()
        self._builder_anomaly_callback: Optional[StepAnomalyCallback] = None
        self._builder_skip_timing: bool = False

    def on_anomaly(self, callback: StepAnomalyCallback) -> "StepBuilder":
        """Register a callback invoked when a timing anomaly is detected.

        The callback receives the step instance and robot::

            drive_forward(25).on_anomaly(my_handler)

            async def my_handler(step, robot):
                ...
        """
        self._builder_anomaly_callback = callback
        return self

    def skip_timing(self) -> "StepBuilder":
        """Exclude this step from timing anomaly tracking.

        Use for steps whose duration is inherently variable
        (e.g., condition-only drives, user-input waits).
        """
        self._builder_skip_timing = True
        return self

    @abstractmethod
    def _build(self) -> Step:
        """Construct the real Step from collected parameters."""
        raise NotImplementedError

    async def _execute_step(self, robot: "GenericRobot") -> None:
        """Build the step, transfer builder options, and execute it."""
        step = self._build()
        if self._builder_anomaly_callback is not None:
            step._anomaly_callback = self._builder_anomaly_callback
        if self._builder_skip_timing:
            step._skip_timing = True
        await step.run_step(robot)

    def _generate_signature(self) -> str:
        step = self._build()
        return step._generate_signature()
