"""Tests that the installed raccoon package ships complete .pyi stub files.

These tests guard against the regression where native-binding stubs (e.g.
hal.pyi) were generated by the build but never installed alongside the .so
files, causing raccoon-cli codegen to fail with "Could not resolve type".

Run conditions: this file is collected only when raccoon is importable
(conftest.py skips the whole tests/python directory otherwise).
"""

from __future__ import annotations

import ast
import importlib.util
from pathlib import Path

# ---------------------------------------------------------------------------
# Helpers (mirror what raccoon-cli introspection does at runtime)
# ---------------------------------------------------------------------------


def _find_pyi(module_name: str) -> Path | None:
    """Return the .pyi file for *module_name*, or None if not found."""
    spec = importlib.util.find_spec(module_name)
    if spec is None or spec.origin is None:
        return None
    origin = Path(spec.origin)
    stem = origin.stem.split(".")[0]  # strip .cpython-313-x86_64-linux-gnu
    pyi = origin.parent / f"{stem}.pyi"
    return pyi if pyi.exists() else None


def _class_init_params(pyi: Path, class_name: str) -> dict[str, bool]:
    """Parse *pyi* and return {param_name: is_required} for class *class_name*.__init__."""
    tree = ast.parse(pyi.read_text(encoding="utf-8"))
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.ClassDef) or node.name != class_name:
            continue
        # Pick __init__ with most params (handles @overload)
        best_args: list[ast.arg] = []
        best_defaults: list = []
        for item in node.body:
            if (
                isinstance(item, ast.FunctionDef)
                and item.name == "__init__"
                and len(item.args.args) >= len(best_args)
            ):
                best_args = item.args.args
                best_defaults = item.args.defaults
        first_default = len(best_args) - len(best_defaults)
        return {
            arg.arg: (i < first_default) for i, arg in enumerate(best_args) if arg.arg != "self"
        }
    return {}


def _param_type_annotation(pyi: Path, class_name: str, param_name: str) -> str | None:
    """Return the type annotation string for *param_name* in *class_name*.__init__."""
    tree = ast.parse(pyi.read_text(encoding="utf-8"))
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.ClassDef) or node.name != class_name:
            continue
        for item in node.body:
            if not isinstance(item, ast.FunctionDef) or item.name != "__init__":
                continue
            for arg in item.args.args:
                if arg.arg == param_name and arg.annotation is not None:
                    return ast.unparse(arg.annotation)
    return None


# ---------------------------------------------------------------------------
# hal.pyi — Motor, Servo, DigitalSensor, AnalogSensor
# ---------------------------------------------------------------------------


def test_hal_pyi_is_installed():
    """hal.pyi must be installed alongside hal.cpython-*.so.

    If this fails: the CMakeLists.txt install rule for staging .pyi files is
    missing or the build was not re-run after adding it.
    """
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, (
        "hal.pyi not found next to the installed raccoon.hal native module.\n"
        "Fix: ensure the CMakeLists.txt installs staging .pyi files and rebuild raccoon."
    )


def test_hal_pyi_exports_expected_classes():
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, "hal.pyi not installed (see test_hal_pyi_is_installed)"
    source = pyi.read_text(encoding="utf-8")
    for cls in ("Motor", "Servo", "DigitalSensor", "AnalogSensor", "IMU"):
        assert f"class {cls}" in source, f"class {cls} missing from hal.pyi"


def test_motor_init_params():
    """Motor.__init__ must expose port (required), inverted (optional), calibration (optional)."""
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, "hal.pyi not installed"
    params = _class_init_params(pyi, "Motor")
    assert "port" in params, f"Motor.port missing from hal.pyi; found: {list(params)}"
    assert params["port"] is True, "Motor.port must be required (no default)"
    assert "inverted" in params, "Motor.inverted missing from hal.pyi"
    assert params["inverted"] is False, "Motor.inverted must be optional (has default)"
    assert "calibration" in params, "Motor.calibration missing from hal.pyi"
    assert params["calibration"] is False, "Motor.calibration must be optional (has default)"


def test_motor_calibration_type_annotation():
    """Motor.calibration must be annotated with raccoon.foundation.MotorCalibration."""
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, "hal.pyi not installed"
    ann = _param_type_annotation(pyi, "Motor", "calibration")
    assert ann is not None, "Motor.calibration has no type annotation in hal.pyi"
    assert (
        "MotorCalibration" in ann
    ), f"Motor.calibration annotation should reference MotorCalibration, got: {ann!r}"


def test_servo_init_params():
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, "hal.pyi not installed"
    params = _class_init_params(pyi, "Servo")
    assert "port" in params, f"Servo.port missing from hal.pyi; found: {list(params)}"
    assert params["port"] is True, "Servo.port must be required"


def test_digital_sensor_init_params():
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, "hal.pyi not installed"
    params = _class_init_params(pyi, "DigitalSensor")
    assert "port" in params, f"DigitalSensor.port missing from hal.pyi; found: {list(params)}"
    assert params["port"] is True, "DigitalSensor.port must be required"


def test_analog_sensor_init_params():
    pyi = _find_pyi("raccoon.hal")
    assert pyi is not None, "hal.pyi not installed"
    params = _class_init_params(pyi, "AnalogSensor")
    assert "port" in params, f"AnalogSensor.port missing from hal.pyi; found: {list(params)}"
    assert params["port"] is True, "AnalogSensor.port must be required"


# ---------------------------------------------------------------------------
# foundation.pyi — MotorCalibration
# ---------------------------------------------------------------------------


def test_foundation_pyi_is_installed():
    pyi = _find_pyi("raccoon.foundation")
    assert pyi is not None, (
        "foundation.pyi not found.\n"
        "Fix: ensure CMakeLists.txt installs staging .pyi files and rebuild raccoon."
    )


def test_motor_calibration_init_params():
    """MotorCalibration.__init__ must expose ticks_to_rad and vel_lpf_alpha."""
    pyi = _find_pyi("raccoon.foundation")
    assert pyi is not None, "foundation.pyi not installed"
    params = _class_init_params(pyi, "MotorCalibration")
    assert params, "MotorCalibration has no __init__ params in foundation.pyi"
    assert "ticks_to_rad" in params, f"MotorCalibration.ticks_to_rad missing; found: {list(params)}"
    assert (
        "vel_lpf_alpha" in params
    ), f"MotorCalibration.vel_lpf_alpha missing; found: {list(params)}"
