"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import libstp_api.exlcm.key_value_t

class dict_t(object):
    __slots__ = ["values_count", "entries"]

    __typenames__ = ["int32_t", "libstp_api.exlcm.key_value_t"]

    __dimensions__ = [None, ["values_count"]]

    def __init__(self):
        self.values_count = 0
        self.entries = []

    def encode(self):
        buf = BytesIO()
        buf.write(dict_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.values_count))
        for i0 in range(self.values_count):
            assert self.entries[i0]._get_packed_fingerprint() == libstp_api.exlcm.key_value_t._get_packed_fingerprint()
            self.entries[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dict_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dict_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = dict_t()
        self.values_count = struct.unpack(">i", buf.read(4))[0]
        self.entries = []
        for i0 in range(self.values_count):
            self.entries.append(libstp_api.exlcm.key_value_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if dict_t in parents: return 0
        newparents = parents + [dict_t]
        tmphash = (0x2f5d5d994bff7628+ libstp_api.exlcm.key_value_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if dict_t._packed_fingerprint is None:
            dict_t._packed_fingerprint = struct.pack(">Q", dict_t._get_hash_recursive([]))
        return dict_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dict_t._get_packed_fingerprint())[0]

